apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "netmaker.labels" . | nindent 4 }}
    {{- if .Values.service.uiLabels }}
    {{- toYaml .Values.service.uiLabels | nindent 4 }}
    {{- end }}

  name: '{{ include "netmaker.fullname" . }}-ui'
  {{- if .Values.service.uiAnnotations }}
  annotations:
    {{- toYaml .Values.service.uiAnnotations | nindent 4 }}
  {{- end }}

spec:
  ports:
  - port: {{ .Values.service.uiPort }}
    protocol: TCP
    targetPort: {{ .Values.service.uiPort }}
  selector:
    app: '{{ include "netmaker.fullname" . }}-ui'
  sessionAffinity: None
  type: '{{ .Values.service.type }}'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "netmaker.labels" . | nindent 4 }}
  name: '{{ include "netmaker.fullname" . }}-rest'
spec:
  ports:
  - name: rest
    port: {{ .Values.service.restPort }}
    protocol: TCP
    targetPort: {{ .Values.service.restPort }}
  selector:
    app: '{{ include "netmaker.fullname" . }}'
  sessionAffinity: None
  type: {{ .Values.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "netmaker.labels" . | nindent 4 }}
  name: '{{ include "netmaker.fullname" . }}-grpc'
spec:
  ports:
  - name: rest
    port: {{ .Values.service.grpcPort }}
    protocol: TCP
    targetPort: {{ .Values.service.grpcPort }}
  selector:
    app: '{{ include "netmaker.fullname" . }}'
  sessionAffinity: None
  type: {{ .Values.service.type }}
{{- if .Values.wireguard.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "netmaker.labels" . | nindent 4 }}
  name: '{{ include "netmaker.fullname" . }}-wireguard'
spec:
  externalTrafficPolicy: Local
  type: NodePort
  ports:
  {{- $count := (add .Values.wireguard.networkLimit 1 | int) }}
  {{- range untilStep 1 $count 1 }}
  {{- $port := (add $.Values.wireguard.baseUdpPort . | int) }}
  - port: {{ $port }}
    nodePort: {{ $port }}
    protocol: UDP
    targetPort: {{ $port }}
    name: wg-iface-{{ $port }}
  {{- end }}
  selector:
    app: '{{ include "netmaker.fullname" . }}'
{{- end }}